### ISSUE TITLE
Modifications of the Customers table to add COWOA_order

### ISSUE THREAD

**Issue by bislewl** [DivaVocals/zen_COWOA#17]
/New_Installation/3_ZenCart_1.5.3/YOUR_ADMIN/includes/init_includes/init_cowoa_config.php
Line 17 should alter the Orders Table, NOT the customers table.

Additionally the use of the $sniffer global should be being used per DrByte

Replace Lines:
4-19 

with somehting like:
global $sniffer;
if (!$sniffer->field_exists(TABLE_ORDERS, 'COWOA_order'))  $db->Execute("ALTER TABLE " . TABLE_ORDERS . " ADD COWOA_order tinyint(1) NOT NULL default 0;");
if (!$sniffer->field_exists(TABLE_CUSTOMERS, 'COWOA_account'))  $db->Execute("ALTER TABLE " . TABLE_CUSTOMERS . " ADD COWOA_account tinyint(1) NOT NULL default 0;");

**Comment by DivaVocals** [comment]
Oh CRAP Larry!!! How the heck did I miss this!!! :disappointed: I'll have a looksee.. But in the meantime if you wanted to submit a pull request for this change, we are happy for another contributor round these parts.. :smile:
