### ISSUE TITLE
No sidebox option

### ISSUE THREAD

**Issue by Robbie269** [DivaVocals/zen_COWOA#22]
Chose sideboxes off option during checkout. When I logoff the confirmation page fills half the screen and the rest is white. Same thing happens with an empty cart. The page is not broken but it looks broken.
Personally I do not think there is any problem having the sideboxes on for these 2 pages and it looks better.

**Comment by DivaVocals** [comment]
This isn't a bug as much as it is a preference.. jeking posted the correct solutiom for you on the Zen Cart forum. https://www.zen-cart.com/showthread.php?196995-COWOA-(for-ZC-v1-5-x)&p=1307233#post1307233
