### ISSUE TITLE
checkout_confirmation:  missing <?php; code shows on page

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_COWOA#25]
When the checkout_confirmation page displays, the characters `if ($_SESSION['cart']->show_total() != 0) { ?> ` show above the Delivery/Shipping information.

Within /includes/templates/{non-responsive}/templates/tpl_checkout_confirmation_default.php, line 45 is missing the <?php leadin:
` if ($_SESSION['cart']->show_total() != 0) {  ?>`

The statement should be coded as
`<?php  if ($_SESSION['cart']->show_total() != 0) {  ?>`

Added: running the zc155 path within the installation.

**Comment by lat9** [comment]
Unfortunately, there's more!  Simply correcting that statement leads to an "unexpected end-of-file"; it looks like the closing brace for that if-statement should be placed at line 84 within that module.

**Comment by DivaVocals** [comment]
See if the latest commits addressed this 5524018 & ba76b54
